### ISSUE TITLE
undefined reference to `pow'

### ISSUE THREAD

**Issue by TwiN** [rpi-ws281x/rpi-ws281x-go#12]
Following the `Compiling directly on the Raspberry Pi` instructions, I am getting the following error when calling the library from a Go application:

```
# github.com/rpi-ws281x/rpi-ws281x-go
/usr/bin/ld: //usr/local/lib/libws2811.a(ws2811.o): in function `ws2811_set_custom_gamma_factor':
/home/pi/workspace/rpi_ws281x/ws2811.c:1298: undefined reference to `pow'
collect2: error: ld returned 1 exit status
```

**Comment by TwiN** [comment]
Seems to have started as of https://github.com/jgarff/rpi_ws281x/pull/409

Building the previous commit (063b7808408b0a21ff4dc23b0ed031a91371b2a6) works as intended, I created an upstream issue to track it: https://github.com/jgarff/rpi_ws281x/issues/424

**Comment by supcik** [comment]
Thank you for your message. I'll fix it as soon as possible.

**Comment by supcik** [comment]
It seems that the `scons` script of jgarff/rpi_ws281x is broken. I will switch to `cmake`.

**Comment by Gadgetoid** [comment]
`cmake` works for me, but you will have to:

```patch
pi@raspberrypi:~/rpi-ws281x-go $ git diff
diff --git a/ws2811_arm.go b/ws2811_arm.go
index c62ff5e..48c00eb 100644
--- a/ws2811_arm.go
+++ b/ws2811_arm.go
@@ -26,7 +26,7 @@ package ws2811
 // #include <stdint.h>
 // #include <stdlib.h>
 // #include <string.h>
-// #include <ws2811.h>
+// #include <ws2811/ws2811.h>
 import "C"

 import (
```

I'm not sure exactly why scons has broken in this respect, but it's a bit of a clunky build system anyway. Came here to recommend a switch to CMake after the tests passed for me using it.

**Comment by supcik** [comment]
> `cmake` works for me, but you will have to:
> 
> ```diff
> pi@raspberrypi:~/rpi-ws281x-go $ git diff
> diff --git a/ws2811_arm.go b/ws2811_arm.go
> index c62ff5e..48c00eb 100644
> --- a/ws2811_arm.go
> +++ b/ws2811_arm.go
> @@ -26,7 +26,7 @@ package ws2811
>  // #include <stdint.h>
>  // #include <stdlib.h>
>  // #include <string.h>
> -// #include <ws2811.h>
> +// #include <ws2811/ws2811.h>
>  import "C"
> 
>  import (
> ```
> 
> I'm not sure exactly why scons has broken in this respect, but it's a bit of a clunky build system anyway. Came here to recommend a switch to CMake after the tests passed for me using it.

Thank you for the input. I guess that you are right and scons is fine... but as you wrote, CMake is probably better suited here.

**Comment by supcik** [comment]
OK. The compilation works again. I will also add a wrapper for the `ws2811_set_custom_gamma_factor` to complete the go bindings.

**Comment by supcik** [comment]
I just made the version v1.0.6 and as far as I can see, it seems to fix this bug. @TwinProduction, can you please confirm that it is OK for you ?

**Comment by TwiN** [comment]
@supcik Sorry for the delay - yes, the problem has been resolved.

Thank you!
