### ISSUE TITLE
Compiling on RPI4 using ws2811_sim.go

### ISSUE THREAD

**Issue by onnenon** [rpi-ws281x/rpi-ws281x-go#13]
As stated, when compiling on a RPI4 it is using `ws2811_sim.go`.

I attempted to fix this by forking and changing the build constraints to be:
  * `ws2811_arm.go` to `// +build arm arm64`
  * `ws2811_sim.go` to `// +build !arm,!arm64` 

After trying quite a few combinations of build constraints it is still falling into using sim. 

My understanding of build constraints is limited, so I'm sure there is something simple I am overlooking.

I have verified that it is a build constraint, and not my failure to install the C library by combining all of the necessary code into `ws2811.go` and my code controls my neopixel array as expected.

### go env:
```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/sonnen/.cache/go-build"
GOENV="/home/sonnen/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sonnen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sonnen/projects/lights/lights_go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build382712525=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by supcik** [comment]
Thank you for your feedback. I haven't implemented the code for the ARM64 architecture yet because, until now, nobody seemed to need it. But with your issue, I will look into the matter.

**Comment by onnenon** [comment]
Hey no problem. Thank you for the quick response. If there is any way I can help troubleshoot, or documentation you could point me to I could try to implement it and submit a PR. 

I'm not sure why changing the build flags wasn't working. Is it something to do with the file name as well?

**Comment by supcik** [comment]
I don't think that the file names are relevant and what you did seems OK to me. I have to make some experiments. Are you compiling on the RPi 4 directly or are you cross-compiling ? And what OS/version do you have on the RPi 4 (Ubuntu, Pi OS) ?

**Comment by supcik** [comment]
Actually the file name might be relevant :

https://golang.org/cmd/go/#hdr-Build_constraints

----- BEGIN CITATION -----
If a file's name, after stripping the extension and a possible _test suffix, matches any of the following patterns:

```
*_GOOS
*_GOARCH
*_GOOS_GOARCH
```

(example: source_windows_amd64.go) where GOOS and GOARCH represent any known operating system and architecture values respectively, then the file is considered to have an implicit build constraint requiring those terms (in addition to any explicit constraints in the file).
----- END CITATION -----

**Comment by supcik** [comment]
So you can try to rename `ws2811_arm.go` to `ws2811_hw.go` (for Hardware)

**Comment by onnenon** [comment]
Looks like the file name was the missing piece. I caught that in the docs after struggling all night trying to get it to work.

**Comment by supcik** [comment]
Thank you @onnenon. I just merged your PR in the master branch. Please, let me know if I need to do something else. If you are happy with the solution, could you please leave a comment and close this issue ? Thank you in advance.

**Comment by onnenon** [comment]
Hey thank you. PR #14 resolves this. I'll go ahead and close it.

**Comment by finack** [comment]
Hi @supcik! Just learning go and spent more time then I should have figuring out why I could not get a hello world app to run natively on a Raspberry pi 4. Turns out `go mod` is pulling v1.0.6 and I was reading master :) 

Just in case this helps other n00bs, `go get github.com/rpi-ws281x/rpi-ws281x-go@master` fixed me right up!

Could you publish v1.0.7 when you have a chance?

**Comment by supcik** [comment]
Thank you @finack for your message. I just published the tag v1.0.7. Could you please let me know if you can now use the module without @master ?

**Comment by finack** [comment]
Hi @supcik! `got get` pulled down the latest, v1.0.8! Thanks for the update!

**Comment by supcik** [comment]
👍🏼
