### ISSUE TITLE
ws2811.h: No such file or directory on Raspberry Pi 4

### ISSUE THREAD

**Issue by gandaldf** [rpi-ws281x/rpi-ws281x-go#18]
Hi all, I followed the rpi_ws281x documentation, I compiled and installed the library (I have a `libws2811.a` in `/usr/local/lib` and I have a `ws2811 folder` with some .h files in `/usr/local/include`); I was abled to run the test succesfully too.
I downloaded the Go wrapper with:
`go get github.com/rpi-ws281x/rpi-ws281x-go`
I copied `basic.go` example in my project folder `/home/pi/go/src/ws281x/main.go` and then I've tried with:
`go run main.go` and `go build` but in both cases I get this error:
```
# github.com/jgarff/rpi_ws281x/golang/ws2811
In file included from ../../pkg/mod/github.com/jgarff/rpi_ws281x@v0.0.0-20201106090144-3a20f1bdd740/golang/ws2811/ws2811.go:38:
./ws2811.go.h:30:10: fatal error: ws2811.h: No such file or directory
 #include <ws2811.h>
          ^~~~~~~~~~
compilation terminated.
```
My Go version is:
`go version go1.14.4 linux/arm`

My Go env is:
```
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pi/go/src/ws281x/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build756845583=/tmp/go-build -gno-record-gcc-switches"
```
I would really like to be able to compile my code on this machine, I write and run my code on this specific hardware and I don't need cross-compile so I skipped the Docker compilation.
Is there something I missed? Could anyone please help me with this problem?

**Comment by supcik** [comment]
Hello. Can you please list all the files in your `/usr/local/include` ? (e.g. using `find /usr/local/include`).

**Comment by gandaldf** [comment]
Hi and thank you for your reply.
Here is the output of `find /usr/local/include`:
```
/usr/local/include
/usr/local/include/ws2811
/usr/local/include/ws2811/rpihw.h
/usr/local/include/ws2811/pcm.h
/usr/local/include/ws2811/dma.h
/usr/local/include/ws2811/ws2811.h
/usr/local/include/ws2811/mailbox.h
/usr/local/include/ws2811/pwm.h
/usr/local/include/ws2811/gpio.h
/usr/local/include/ws2811/clk.h
```

**Comment by supcik** [comment]
It looks good. What bothers me is this line :

```
# github.com/jgarff/rpi_ws281x/golang/ws2811
```

This is from an old version of the go-wrapper and this is no longer maintained.
The new wrapper is https://github.com/rpi-ws281x/rpi-ws281x-go

I guess that you used the `basic.go` from the  old wrapper (https://github.com/jgarff/rpi_ws281x/blob/master/golang/examples/basic.go) and this does no longer work. Perhaps we should ask the maintainer of the C library to remove this old wrapper.

Can you try with examples from the new wrapper (https://github.com/rpi-ws281x/rpi-ws281x-go/tree/master/examples) ?

**Comment by gandaldf** [comment]
Now it works!
Oh god, I completely missed that `examples` folder.
Someone really should ask the maintainer of the C library to remove the old wrapper and maybe the language-specific examples; in this way anyone is forced to check the `examples` folder in the language-binding repo.
