### ISSUE TITLE
go get deprecation

### ISSUE THREAD

**Issue by WegnerDan** [rpi-ws281x/rpi-ws281x-go#20]
The dockerfile contains `go get` which was deprecated some time ago. 
https://github.com/rpi-ws281x/rpi-ws281x-go/blob/bcf6db0add9ba60472952bb43b8abc69de9325d8/docker/app-builder/Dockerfile#L26C1-L26C1

https://go.dev/doc/go-get-install-deprecation

I've tried using go install, but I couldn't get it to work (I have no idea what I'm doing in golang)  
I could get it to work by changing `FROM golang:latest` to `FROM golang:1.15.15` but that's not a solution

**Comment by supcik** [comment]
Thank you for your message. I will update the project to fix this issue.

**Comment by supcik** [comment]
I updated the examples to use go modules, and I updated the README file. This should fix this issue. Can you please check this latest version ?

**Comment by WegnerDan** [comment]
Thank you, it's working now!
